name: 'download dir with zip'
on: 
  repository_dispatch:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3

      - name: Clone code
        run: |
          echo $PWD
          sudo mkdir -p /lede
          sudo chown $USER:$GROUPS /lede
          cd /lede
          git clone https://github.com/coolsnowwolf/lede

      - name: archive release
        uses: thedoctor0/zip-release@main
        with:
          path: /lede
          type: 'zip'
          filename: 'openwrt.zip'
