name: 'download dir with zip'
jobs:
  push-core:
    run-on: ubuntu-18.04.6
    steps:
      release:
        - name: 'checkout'
        - uses: actions/checkout@v3

        - name: Clone code
        - run: |
            echo $PWD
            sudo mkdir -p /lede
            sudo chown $USER:$GROUPS /lede
            sudo cd /lede
            git clone https://github.com/coolsnowwolf/lede

        - name: archive release
          uses: thedoctor0/zip-release@main
          with:
            path: /lede
            type: 'zip'
            filename: 'openwrt.zip'

