name: 'download dir with zip'
on: 
  repository_dispatch:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3

      - name: Clone code
        run: |
          echo $PWD
          sudo mkdir -p /lede
          sudo chown $USER:$GROUPS /lede
          cd /lede
          git clone https://github.com/coolsnowwolf/lede

      - name: archive release
        uses: thedoctor0/zip-release@main
        with:
          path: /lede
          type: 'zip'
          filename: 'openwrt.zip'
          
      - name: Generate release tag
        id: tag
        if: success()
        run: |
          echo $PWD
          ls -a
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          
      - name: release
        uses: softprops/action-gh-release@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: openwrt.zip
