name: upload config

on: push
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@main
      
      - name: initialization env
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
      
      - name: create .config
        working-directory: /workdir
        run: |
          sudo mkdir openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
          cd openwrt
          sudo touch config.txt
          ls -l config.txt
          sudo chmod 770 config.txt
          sudo echo "config" > config.txt
          ls -a
          
      - name: Upload config
        uses: actions/upload-artifact@main
        with:
          name: config
          path: openwrt/config.txt
          if-no-files-found: error
