name: upload config

on: push
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@main
      
      - name: initialization env
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
      
      - name: create .config
        working-directory: /workdir
        run: |
          sudo mkdir openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
          cd openwrt
          sudo touch config.txt
          ls -l config.txt
          
      - name: archive release
        uses: thedoctor0/zip-release@main
        with:
          path: openwrt
          type: 'zip'
          filename: 'openwrt.zip'
        
      - name: echo dir
        run: |
          echo $PWD
          ls -a
          echo "FILE_NAME=openwrt.zip" >> $GITHUB_ENV
      - name: Upload zip directory
        uses: actions/upload-artifact@main
        if: success() && !cancelled()
        with:
          name: OpenWrt_Packages
          path: ${{ env.FILE_NAME }}
          if-no-files-found: error
